[package]
name = "carriots-client"
version = "0.3.1"
authors = ["Samuel de Ancos <sdeancos@gmail.com>"]

[dependencies]
docopt = "0.8.3"
reqwest = "0.8.5"
hyper = "*"

[profile.release]
lto = true
panic = 'abort'